model_path = 'path_to_model_data' 

logreg_col_drop_dict = {
    0: ['rr-grp-mean-yearly-mean',
       'rr-grp-mean-yearly-sum',
       'tg-grp-mean-days-above-5degC-monthly-ratio',
       'tn-grp-mean-daily-temp-range-monthly-mean',
       'tx-grp-mean-monthly-max',
       'cervus_elaphus'],
    1: ['cervus_elaphus',
        'rr-grp-mean-yearly-mean',
        'tg-grp-mean-june-mean',
        'tx-grp-mean-spring-days-above-40f',
        'tn-grp-mean-dec-min',
        'tn-grp-mean-range-annual-mean'],
    2: ['cervus_elaphus',
        'rr-grp-mean-yearly-mean',
        'rr-grp-mean-yearly-sum',
        'rr-grp-mean-january-sum',
        'tg-grp-mean-days-above-5degC-monthly-ratio',
        'tx-grp-mean-spring-days-above-40f',
        'tg-grp-mean-june-mean',
        'tn-grp-mean-monthly-min',
        'tn-grp-mean-daily-temp-range-monthly-mean',
        'tn-grp-mean-monthly-min']
}

xgboost_col_drop_dict = {
    0: ['cervus_elaphus',
        'rr-grp-mean-yearly-sum',
        'tg-grp-mean-mean-temp-driest-qtr',
        'tg-grp-mean-mean-temp-driest-qtr',
        'tg-grp-mean-yearly-mean',
        'tx-grp-mean-spring-days-above-40f',
        'tn-grp-mean-range-annual-mean',
        'tx-grp-mean-monthly-max'
    ],
    1: ['cervus_elaphus',
        'rr-grp-mean-yearly-sum',
        'tg-grp-mean-june-mean',
        'tx-grp-mean-spring-days-above-40f',
        'tn-grp-mean-dec-min',
        'tn-grp-mean-daily-temp-range-monthly-mean'
    ],
    2: ['cervus_elaphus',
        'rr-grp-mean-yearly-mean',
        'rr-grp-mean-yearly-sum',
        'tg-grp-mean-mean-temp-driest-qtr',
        'tg-grp-mean-days-above-5degC-monthly-ratio',
        'tx-grp-mean-spring-days-above-40f',
        'tg-grp-mean-june-mean',
        'tn-grp-mean-daily-temp-range-monthly-mean',
        'tn-grp-mean-dec-min']
}

adm_shp_path_dict = {
    'NO' : '../../data/shapefiles/adm2_norway_shp/NOR_adm2.shp',
    'DE' : '../../data/shapefiles/adm2_germany_shp/DEU_adm2.shp',
    'SE' : '../../data/shapefiles/adm2_sweden_shp/SWE_adm2.shp',
    'DK' : '../../data/shapefiles/adm2_denmark_shp/DNK_adm2.shp',
    'FI' : '../../data/shapefiles/adm3_finland_shp/FIN_adm3.shp',
    'EE' : '../../data/shapefiles/adm2_estonia_shp/EST_adm2.shp',
    'LV' : '../../data/shapefiles/adm2_latvia_shp/LVA_adm2.shp',
    'LT' : '../../data/shapefiles/adm2_lithuania_shp/LTU_adm2.shp',
    'PL' : '../../data/shapefiles/adm2_poland_shp/POL_adm2.shp',
    'FR' : '../../data/shapefiles/adm3_france_shp/FRA_adm3.shp',
    'SK' : '../../data/shapefiles/adm2_slovakia_shp/SVK_adm2.shp',
    'CH' : '../../data/shapefiles/adm2_switzerland_shp/CHE_adm2.shp',
    'NL' : '../../data/shapefiles/adm2_netherlands_shp/NLD_adm2.shp',
    'CZ' : '../../data/shapefiles/adm2_czech_shp/CZE_adm2.shp',
    'AT' : '../../data/shapefiles/adm2_austria_shp/AUT_adm2.shp',
    'IT' : '../../data/shapefiles/adm3_italy_shp/ITA_adm3.shp',
    'SI' : '../../data/shapefiles/adm2_slovenia_shp/SVN_adm2.shp',
    'HR' : '../../data/shapefiles/adm2_croatia_shp/HRV_adm2.shp',
    'BE' : '../../data/shapefiles/adm3_belgium_shp/BEL_adm3.shp',
    'UK' : '../../data/shapefiles/adm2_unitedkingdom_shp/GBR_adm2.shp'
}

ctry_map = {
    'Norway' : 'NO',
    'Germany' : 'DE',
    'Sweden' : 'SE',
    'Denmark' : 'DK',
    'Finland' : 'FI',
    'Estonia' : 'EE',
    'Latvia' : 'LV',
    'Lithuania' : 'LT',
    'Poland' : 'PL',
    'France' : 'FR',
    'Slovakia' : 'SK',
    'Switzerland' : 'CH',
    'Netherlands' : 'NL',
    'Czech Republic' : 'CZ',
    'Czechia' : 'CZ',
    'Austria' : 'AT',
    'Italy' : 'IT',
    'Slovenia' : 'SI',
    'Croatia' : 'HR',
    'Belgium' : 'BE',
    'England' : 'UK',
    'Scotland' : 'UK'
}

cov_dict = {
    'geometry':'geometry',
    'apodemus_flavicollis':'cov-apodemus_flavicollis',
    'apodemus_sylvaticus':'cov-apodemus_sylvaticus',
    'cervus_elaphus':'cov-cervus_elaphus',
    'dama_dama':'cov-dama_dama',
    'microtus_subterraneus':'cov-microtus_subterraneus',
    'myodes_glareolus':'cov-myodes_glareolus',
    'landcover':'cov-landcover',
    'elev':'cov-elev',
    'red_deer':'cov-red_deer',
    'roe_deer':'cov-roe_deer',
    'hu-grp-mean-monthly-max':'cov-hu-grp-mean-monthly-max',
    'hu-grp-mean-monthly-mean':'cov-hu-grp-mean-monthly-mean',
    'hu-grp-mean-monthly-min':'cov-hu-grp-mean-monthly-min',
    'rr-grp-mean-january-sum':'cov-rr-grp-mean-january-sum',
    'rr-grp-mean-yearly-sum':'cov-rr-grp-mean-yearly-sum',
    'rr-grp-mean-total-wet-days':'cov-rr-grp-mean-total-wet-days',
    'rr-grp-mean-wet-summer-days':'cov-rr-grp-mean-wet-summer-days',
    'rr-grp-mean-yearly-mean':'cov-rr-grp-mean-yearly-mean',
    'tg-grp-mean-days-above-5degC-monthly-ratio':'cov-tg-grp-mean-days-above-5degC-monthly-ratio',
    'tg-grp-mean-june-mean':'cov-tg-grp-mean-june-mean',
    'tg-grp-mean-mean-temp-driest-qtr':'cov-tg-grp-mean-mean-temp-driest-qtr',
    'tg-grp-mean-yearly-mean':'cov-tg-grp-mean-yearly-mean',
    'tn-grp-mean-dec-min':'cov-tn-grp-mean-dec-min',
    'tn-grp-mean-monthly-min':'cov-tn-grp-mean-monthly-min',
    'tn-grp-mean-daily-temp-range-monthly-mean':'cov-tn-grp-mean-daily-temp-range-monthly-mean',
    'tn-grp-mean-range-annual-mean':'cov-tn-grp-mean-range-annual-mean',
    'tx-grp-mean-monthly-max':'cov-tx-grp-mean-monthly-max',
    'tx-grp-mean-spring-days-above-40f':'cov-tx-grp-mean-spring-days-above-40f',
    'tx-grp-mean-summer-days-above-85f':'cov-tx-grp-mean-summer-days-above-85f',
}